api_version: "0.1"

apps:
  emptyapi:
    path_prefix: "/emptyapi"

    identity:
      collection: identity
      username:
        unique: true
        required: true
      email:
        enabled: true
        unique: false
        required: false
      additional:
        - is_superuser:
            internal: true
        - first_name:
        - last_name:
        - is_staff:
            internal: true

    authN:
      - type: "password_based"
        authZ: jwt
        config:
          main_hasher: django
          collection: pwbased
          storage: one_db

    authZ:
      - type: "jwt"
        name: jwt
        config:
          sub: true
          aud: ["emptyapi"]
          iat: true
          jti: 0
          alg: "RS256"
          sign_key: jwk_file
          verify_keys: [jwk_file]
          payload: "./examples/django/emptyapi/jwt_payload.json.tmpl"

storages:
  - type: "postgresql"
    name: one_db
    config:
      url: "postgresql://root:password@localhost:5432/aureole"

collections:
  - type: "identity"
    name: identity
    config:
      name: "auth_user"
      pk: "id"
      fields_map:
        id: "id"
        username: "username"
        email: "email"
        last_name: "last_name"
        first_name: "first_name"
        is_active: "is_active"
        created: "date_joined"
        is_superuser:
          name: "is_superuser"
          default: false
        is_staff:
          name: "is_staff"
          default: false

  - type: "pwbased"
    name: pwbased
    parent: identity
    config:
      fields_map:
        password: "password"

hashers:
  - type: "pbkdf2"
    name: django

crypto_keys:
  - type: "jwk"
    name: jwk_file
    config:
      path: "lab/keys/keys.json"