api_version: "0.1"

apps:
  emptyapi:
    path_prefix: "/emptyapi"

    identity:
      id:
        enabled: true
        unique: true
        required: true
        credential: false
      username:
        enabled: true
        unique: true
        required: true
        credential: true
      phone:
        enabled: false
      email:
        enabled: true
        unique: false
        required: false
        credential: true
      additional:
        - is_superuser:
            unique: false
            required: false
            internal: true
        - first_name:
            unique: false
            required: false
            internal: false
        - last_name:
            unique: false
            required: false
            internal: false
        - is_staff:
            unique: false
            required: false
            internal: true

    authN:
      - type: "password_based"
        path_prefix: "/"
        authZ: jwt
        config:
          main_hasher: django
          compat_hashers: [ ]
          storage: one_db
          login:
            path: "/login"
            fields_map:
              username: "{$.username}"
              password: "{$.password}"
          register:
            path: "/register"
            login_after: true
            fields_map:
              username: "{$.username}"
              email: "{$.email}"
              phone: "{$.phone}"
              password: "{$.password}"
              first_name: "{$.first_name}"
              last_name: "{$.last_name}"

    authZ:
      - type: "jwt"
        name: jwt
        path_prefix: "/"
        config:
          iss: "Aureole Server"
          sub: true
          aud: ["emptyapi"]
          nbf: 0
          iat: true
          jti: 0
          access_bearer: "header"
          refresh_bearer: "body"
          alg: "RS256"
          sign_key: jwk_file
          verify_keys: [ jwk_file ]
          access_exp: 900
          refresh_exp: 7890000
          refresh_url: "/refresh"
          payload: "./examples/django/emptyapi/jwt_payload.json.tmpl"

storages:
  - type: "postgresql"
    name: one_db
    config:
      url: "postgresql://root:password@localhost:5432/aureole"

hashers:
  - type: "pbkdf2"
    name: django
    config:
      func: "sha256"
      iterations: 26000
      salt_length: 22
      key_length: 32

crypto_keys:
  - type: "jwk"
    name: jwk_file
    config:
      path: "lab/keys/keys.json"