api_version: "0.1"

apps:
  hasura-api:
    path_prefix: "/hasura-api"

    identity:
      collection: identity
      username:
        unique: true
        required: true

    authN:
      - type: "password_based"
        authZ: jwt
        config:
          main_hasher: django
          collection: pwbased
          storage: one_db

    authZ:
      - type: "jwt"
        name: jwt
        config:
          sub: true
          aud: ["hasura-api"]
          iat: true
          jti: 0
          alg: "RS256"
          sign_key: jwk_file
          verify_keys: [jwk_file]
          payload: "/jwt_payload.json"
          native_queries: "/native.yaml"

storages:
  - type: "postgresql"
    name: one_db
    config:
      url: "postgresql://root:password@postgres:5432/aureole"

collections:
  - type: "identity"
    name: identity
    config:
      name: "users"
      pk: "id"
      fields_map:
        id: "id"
        username: "username"
        email: "email"
        phone: "phone"
        is_active: no
        created: no

  - type: "pwbased"
    name: pwbased
    parent: identity
    config:
      fields_map:
        password: "password"

hashers:
  - type: "pbkdf2"
    name: django

crypto_keys:
  - type: "jwk"
    name: jwk_file
    path_prefix: "/keys"
    config:
      path: "/keys.json"