apiVersion: "0.1"

apps:
  one:
    pathPrefix: "/one"
    data: "Hello world!"
    db:
      dsn: "postgresql://admin:admin@localhost:5432/gouth?search_path=public"
    auth:
      useCustomCollection: true
      authCollection: "users"
      userIdentifier: "username"
      userConfirmation: "password"
      login:
        fields:
          "$.name": "username"
          "$.paswd": "password"
        payload:
          "$.userID": "id"
      register:
        loginAfter: true
        fields:
          "$.name": "username"
          "$.paswd": "password"
          "$.email": "email"
  two:
    pathPrefix: "/two"
    data: "Hello world!"
    db:
      dsn: "mongodb://admin:admin@localhost:27017/gouth"
    auth:
      useCustomCollection: true
      authCollection: "users"
      userIdentifier: "username"
      userConfirmation: "password"
      login:
        fields:
          "$.name": "username"
          "$.paswd": "password"
        payload:
          "$.userID": "id"
      register:
        loginAfter: true
        fields:
          "$.name": "username"
          "$.paswd": "password"
          "$.email": "email"