api_version: "0.1"

apps:
  one:
    path_prefix: "/one"

    authN:
      - type: "password_based"
        url: "/login"
        config:
          main_hasher: argon2
          compat_hashers: []
          storage: one_db
          collection: identity
          user_unique: "{$.name}"
          user_confirm: "{$.passwd}"

    authZ:
      type: "cookie"
      config:
        storage: one_db
        collection: session
        domain: "localhost"
        path: "/"
        max_age: 3600
        secure: true
        http_only: false

    identity_flows:
      - type: register
        config:
          login_after: true
          fields:
            user_unique: "{$.name}"
            user_confirm: "{$.passwd}"
            email: "{$.email}"

  two:
    path_prefix: "/two"

    authN:
      - type: "password_based"
        config:
          main_hasher: argon2
          collection: identity

    authZ:
      type: "jwt"
      config:
        alg: "RS256"
        kid_alg: "docker_registry" # implement docker_registry and default and none
        keys: [rsa]
        payload: "jwt_payload.json"
#          "$.userID": "id"
#          "$.userPosts": "@getUserPosts" raw query

    identity_flows:
      - type: register
        config:
          fields:
            user_unique: "{$.name}"
            user_confirm: "{$.passwd}"
            email: "{$.email}"

storages:
  - name: one_db
    config:
      connection_url: "postgresql://root:password@localhost:5432/test?sslmode=disable&search_path=public"

  - name: two_db
    config:
      adapter: "postgresql"
      username: "root"
      password: "password"
      host: "localhost"
      port: "5432"
      db_name: "test"
      options:
        sslmode: "disable"
        search_path: "public"

collections:
  - type: "identity"
    name: identity
    #storage: one_db
    config:
      use_existent: true
      name: "users"
      pk: "id"
      user_unique: "username"
      user_confirm: "password"

  - type: "session"
    name: session
    #storage: one_db
    config:
      use_existent: false
      name: "sessions"
      pk: "id"
      # todo: fill rest

hashers:
  - type: "argon2"
    name: argon2
    config:
      kind: "argon2i"
      iterations: 1
      parallelism: 1
      salt_length: 16
      key_length: 16
      memory: 16384

  - type: "pbkdf2"
    name: django
    config:
      func: "sha1"
      iterations: 1
      salt_length: 16
      key_length: 16

crypto_keys:
  - type: "rsa"
    driver: "file"
    name: rsa
    config:
      path: "./private.pem"
