api_version: "0.1"

apps:
  one:
    path_prefix: "/one"
    db:
      connection_url: "postgresql://admin:admin@localhost:5432/gouth?search_path=public"
    auth:
      use_custom_collection: true
      user_collection:
        name: "users"
        pk: "id"
        user_id: "username"
        user_confirm: "password"
      login:
        fields:
          "$.name": "username"
          "$.passwd": "password"
        payload:
          "$.userID": "id"
      register:
        login_after: true
        fields:
          "$.name": "username"
          "$.passwd": "password"
          "$.email": "email"
  two:
    path_prefix: "/two"
    db:
      connection_url: "mongodb://admin:admin@localhost:27017/gouth"
    auth:
      use_custom_collection: true
      user_collection:
        name: "users"
        user_id: "username"
        user_confirm: "password"
      login:
        fields:
          "$.name": "username"
          "$.passwd": "password"
        payload:
          "$.userID": "_id"
      register:
        login_after: true
        fields:
          "$.name": "username"
          "$.passwd": "password"
          "$.email": "email"