package main

import _ "aureole/plugins/storage/postgresql"
import _ "aureole/plugins/authn/pwbased"
import _ "aureole/plugins/pwhasher/argon2"
import _ "aureole/plugins/pwhasher/pbkdf2"
import _ "aureole/plugins/sender/email"
import _ "aureole/plugins/authz/jwt"
import _ "aureole/plugins/cryptokey/jwk"
import _ "aureole/plugins/authn/phone"
import _ "aureole/plugins/sender/twilio"
import _ "aureole/plugins/authn/email"
import _ "aureole/plugins/cryptokey/pem"
import _ "aureole/plugins/authn/google"
import _ "aureole/plugins/authn/vk"
import _ "aureole/plugins/authn/facebook"
import _ "aureole/plugins/authn/apple"
import _ "aureole/plugins/admin/urls"
