version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "aureole"
    ports:
      - ':5432'
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]