version: '3'

services:
  aureole:
    image: aureolecloud/aureole:latest
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    volumes:
      - ./aureole/config.yml:/config.yml

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://root:password@postgres:5432/aureole
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-aureole}
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - '${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432'
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_connections=on" ]
