api_version: "0.1"

service:
  internal_key: service
  storage: vault_store

apps:
  - name: app
    authn:
      # array of authenticators
    authz:
      # authorizer config

storages:
  # array of storages
hashers:
  # array of hashers
crypo_keys:
  # array of crypto keys
senders:
  # array of senders
admin_plugins:
  # array of admin plugins