name: deploy-docs

on:
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '**schema.json'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install PyYAML ruamel.yaml

      - name: Delete unused descriptions
        run: cd docs && python3 scripts/cleanup_descriptions.py

      - name: Build MD docs
        run: cd docs && python3 scripts/build_md_docs.py

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.0
        with:
          node-version: '14'

      # install dependencies if the cache did not hit
      - name: Install dependencies
        run: cd docs/vuepress_docs && yarn install --frozen-lockfile

      # run build script
      - name: Build VuePress site
        run: cd docs/vuepress_docs && yarn docs:build

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # deploy to docs branch
          target_branch: docs
          # deploy the default output dir of VuePress
          build_dir: docs/vuepress_docs/docs/.vuepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}